export const DATOS_INICIALES = {
	grados: [
		{ id: 1, nombre: "Primer Año Académico (1er año)" },
		{ id: 2, nombre: "Segundo Año Académico (2do año)" },
		{ id: 3, nombre: "Tercer Año Académico (3er año)" },
		{ id: 4, nombre: "Cuarto Año Académico (4to año)" },
		{ id: 5, nombre: "Quinto Año Académico (5to año)" },
	],

	materias: (() => {
		const porAnio = {
			1: [
				{
					nombre: "Matemática I",
					codigo: "MAT-204",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "MAT",
				},
				{
					nombre: "Física I",
					codigo: "FIS-201",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "FIS",
				},
				{
					nombre: "Química I",
					codigo: "QUI-299",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "QUI",
				},
				{
					nombre: "Biología I",
					codigo: "BIO-501",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "BIO",
				},
				{
					nombre: "Lenguaje y Literatura I",
					codigo: "LIT-199",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "LYL",
				},
				{
					nombre: "Historia General",
					codigo: "HIS-101",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "HIS",
				},
				{
					nombre: "Geografía I",
					codigo: "GEO-301",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "GEO",
				},
				{
					nombre: "Computación I",
					codigo: "COM-403",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "COM",
				},
				{
					nombre: "Dibujo I",
					codigo: "DIB-309",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "DIB",
				},
				{
					nombre: "Inglés I",
					codigo: "ING-601",
					area: "idiomas_modernos",
					tipo: "complementaria",
					sigla: "ING",
				},
				{
					nombre: "Deporte I",
					codigo: "DEP-401",
					area: "educacion_fisica_salud",
					tipo: "complementaria",
					sigla: "DEP",
				},
			],
			2: [
				{
					nombre: "Matemática II",
					codigo: "MAT-205",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "MAT",
				},
				{
					nombre: "Física II",
					codigo: "FIS-202",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "FIS",
				},
				{
					nombre: "Química II",
					codigo: "QUI-300",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "QUI",
				},
				{
					nombre: "Biología II",
					codigo: "BIO-502",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "BIO",
				},
				{
					nombre: "Lenguaje y Literatura II",
					codigo: "LIT-200",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "LYL",
				},
				{
					nombre: "Historia II",
					codigo: "HIS-102",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "HIS",
				},
				{
					nombre: "Geografía II",
					codigo: "GEO-302",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "GEO",
				},
				{
					nombre: "Computación II",
					codigo: "COM-404",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "COM",
				},
				{
					nombre: "Dibujo II",
					codigo: "DIB-310",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "DIB",
				},
				{
					nombre: "Inglés II",
					codigo: "ING-602",
					area: "idiomas_modernos",
					tipo: "complementaria",
					sigla: "ING",
				},
				{
					nombre: "Deporte II",
					codigo: "DEP-402",
					area: "educacion_fisica_salud",
					tipo: "complementaria",
					sigla: "DEP",
				},
			],
			3: [
				{
					nombre: "Matemática III",
					codigo: "MAT-206",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "MAT",
				},
				{
					nombre: "Física III",
					codigo: "FIS-203",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "FIS",
				},
				{
					nombre: "Química III",
					codigo: "QUI-301",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "QUI",
				},
				{
					nombre: "Biología III",
					codigo: "BIO-503",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "BIO",
				},
				{
					nombre: "Lenguaje y Literatura III",
					codigo: "LIT-201",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "LYL",
				},
				{
					nombre: "Historia III",
					codigo: "HIS-103",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "HIS",
				},
				{
					nombre: "Geografía III",
					codigo: "GEO-303",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "GEO",
				},
				{
					nombre: "Computación III",
					codigo: "COM-405",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "COM",
				},
				{
					nombre: "Dibujo III",
					codigo: "DIB-311",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "DIB",
				},
				{
					nombre: "Inglés III",
					codigo: "ING-603",
					area: "idiomas_modernos",
					tipo: "complementaria",
					sigla: "ING",
				},
				{
					nombre: "Deporte III",
					codigo: "DEP-403",
					area: "educacion_fisica_salud",
					tipo: "complementaria",
					sigla: "DEP",
				},
			],
			4: [
				{
					nombre: "Matemática IV",
					codigo: "MAT-207",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "MAT",
				},
				{
					nombre: "Física IV",
					codigo: "FIS-204",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "FIS",
				},
				{
					nombre: "Química IV",
					codigo: "QUI-302",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "QUI",
				},
				{
					nombre: "Biología IV",
					codigo: "BIO-504",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "BIO",
				},
				{
					nombre: "Lenguaje y Literatura IV",
					codigo: "LIT-202",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "LYL",
				},
				{
					nombre: "Historia IV",
					codigo: "HIS-104",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "HIS",
				},
				{
					nombre: "Geografía IV",
					codigo: "GEO-304",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "GEO",
				},
				{
					nombre: "Computación IV",
					codigo: "COM-406",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "COM",
				},
				{
					nombre: "Dibujo IV",
					codigo: "DIB-312",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "DIB",
				},
				{
					nombre: "Inglés IV",
					codigo: "ING-604",
					area: "idiomas_modernos",
					tipo: "complementaria",
					sigla: "ING",
				},
				{
					nombre: "Deporte IV",
					codigo: "DEP-404",
					area: "educacion_fisica_salud",
					tipo: "complementaria",
					sigla: "DEP",
				},
			],
			5: [
				{
					nombre: "Matemática V",
					codigo: "MAT-208",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "MAT",
				},
				{
					nombre: "Física V",
					codigo: "FIS-205",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "FIS",
				},
				{
					nombre: "Química V",
					codigo: "QUI-303",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "QUI",
				},
				{
					nombre: "Biología V",
					codigo: "BIO-505",
					area: "exactas_naturales",
					tipo: "troncal",
					sigla: "BIO",
				},
				{
					nombre: "Lenguaje y Literatura V",
					codigo: "LYL-203",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "LYL",
				},
				{
					nombre: "Historia V",
					codigo: "HIS-105",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "HIS",
				},
				{
					nombre: "Geografía V",
					codigo: "GEO-305",
					area: "sociales_humanidades",
					tipo: "troncal",
					sigla: "GEO",
				},
				{
					nombre: "Computación V",
					codigo: "COM-407",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "COM",
				},
				{
					nombre: "Dibujo V",
					codigo: "DIB-313",
					area: "tecnologia_expresion",
					tipo: "complementaria",
					sigla: "DIB",
				},
				{
					nombre: "Inglés V",
					codigo: "ING-605",
					area: "idiomas_modernos",
					tipo: "complementaria",
					sigla: "ING",
				},
				{
					nombre: "Deporte V",
					codigo: "DEP-405",
					area: "educacion_fisica_salud",
					tipo: "complementaria",
					sigla: "DEP",
				},
			],
		};

		let id = 1000;
		const resultado = [];
		for (const [anioStr, lista] of Object.entries(porAnio)) {
			const anioId = Number(anioStr);
			for (const m of lista) {
				resultado.push({
					id: id++,
					anioId,
					sigla: m.sigla,
					nombre: m.nombre,
					codigo: m.codigo,
					area: m.area,
					tipo: m.tipo,
				});
			}
		}
		return resultado;
	})(),

	asignacionesPorGrado: {
		1: [],
		2: [],
		3: [],
		4: [],
		5: [],
	},
};
